export const ADD_MEAL = 'ADD_MEAL';
export const ADD_MEAL_ERROR = 'ADD_MEAL_ERROR';
export const DELETE_MEAL = 'DELETE_MEAL';
export const DELETE_MEAL_ERROR = 'DELETE_MEAL_ERROR';
export const LOAD_ALL_MEALS_ERROR = 'LOAD_ALL_MEALS_ERROR';
export const LOAD_FAVOURITES_ERROR = 'LOAD_FAVOURITES_ERROR';
export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
export const ADD_TO_FAVOURITES_ERROR = 'ADD_TO_FAVOURITES_ERROR';

export const ADD_TO_ORDER = 'ADD_TO_ORDER';
export const REMOVE_FROM_ORDERS = 'REMOVE_FROM_ORDERS';
export const SET_CURRENT = 'SET_CURRENT';
export const LOAD_ALL_MEALS = 'LOAD_ALL_MEALS';
export const LOAD_FAVOURITES = 'LOAD_FAVOURITES';

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_AUTH_MSG = 'CLEAR_AUTH_MSG';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED';
export const UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS';
export const UPDATE_DATA_FAIL = 'UPDATE_DATA_FAIL';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const LOAD_REVIEWS = 'LOAD_REVIEWS';
export const LOAD_REVIEWS_ERROR = 'LOAD_REVIEWS_ERROR';
